export const HOME = "/"
export const LOGIN = "/login"
export const SIGNUP = "/signup"
export const BIO = "/signup/bio"
export const INTEREST = "/signup/interest"
export const HOMEWEB = "/home"
export const FORGOTID = "/forget"
export const PROFILE = "/profile"
